import pytest
from fastapi.testclient import TestClient
from app.main import app
import os

# We need to ensure the model exists for API tests to run
# The model should be generated by ml_pipeline/train_model.py before running pytest
@pytest.fixture
def client():
    # Only return client if model exists, otherwise tests will fail on prediction
    model_path = os.path.join(os.path.dirname(__file__), "..", "models", "complexity_model.pkl")
    if not os.path.exists(model_path):
        pytest.skip("Model not found. Please run ml_pipeline/train_model.py")
    return TestClient(app)

def test_health_check(client):
    response = client.get("/api/health")
    assert response.status_code == 200
    assert response.json() == {"status": "ok"}

def test_analyze_python(client):
    code = "for i in range(n):\n    print(i)"
    response = client.post("/api/analyze", json={"language": "python", "code": code})
    assert response.status_code == 200
    data = response.json()
    assert data["language"] == "python"
    assert "time_complexity" in data
    assert "confidence" in data
    assert "reason" in data
    assert "features" in data
    assert data["features"]["loop_count"] == 1

def test_analyze_java(client):
    code = "for(int i=0; i<n; i++) { System.out.println(i); }"
    response = client.post("/api/analyze", json={"language": "java", "code": code})
    assert response.status_code == 200
    data = response.json()
    assert data["language"] == "java"
    assert "time_complexity" in data
    assert data["features"]["loop_count"] == 1
    
def test_invalid_language(client):
    response = client.post("/api/analyze", json={"language": "c++", "code": "int main() {}"})
    assert response.status_code == 400
    assert "Unsupported language" in response.json()["detail"]
